---
title: "Ragamuffin Reports"
author: "Sam Albers"
date: "`r Sys.Date()`"
output: pdf_document
params: 
  artist: 'buck owens'
  song1: 'foo1'
  song2: 'foo2'
  song1id: 'doo1'
  song2id: 'doo1'
---

```{r, warning=FALSE, echo=FALSE}

ggplot2::theme_set(ggplot2::theme_minimal())

knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      fig.align = "center",
                      fig.width=12,
                      fig.height = 12)

#ggplot2::scale_colour_continuous <- ggplot2::scale_colour_viridis_c

#params <- dplyr::tibble(artist = "merle haggard")
```


```{r, echo=FALSE}
library(spotifyr)
library(dplyr, warn.conflicts = FALSE)
library(usethis)
library(ggplot2)
library(tidyr)
library(purrr)
library(kableExtra)
```

```{r}
raw <- get_artist_audio_features(params$artist)
```

# `r tools::toTitleCase(params$artist)`

## Songs chosen
 1 `r tools::toTitleCase(params$song1)`
 2 `r tools::toTitleCase(params$song2)`

## Key
```{r}
raw %>% 
  count(key_mode, sort = TRUE) 
```

## Time Signature
```{r}
raw %>% 
  count(time_signature, sort = TRUE)
```

## Cumulative Albums
```{r}
cumulative_albums <- raw %>% 
  select(album_release_year, album_name) %>% 
  distinct(.keep_all = TRUE) %>% 
  count(album_release_year) %>% 
  arrange(album_release_year) %>% 
  mutate(albums = cumsum(n))

ggplot(cumulative_albums, aes(x = album_release_year, y = albums)) +
  geom_line()
```

## Audio Features

```{r}
songs <-  map_dfr(c(params$song1id, params$song2id), get_track_audio_features, .id = "songid") %>% 
  select(danceability:tempo, duration_ms, songid) %>% 
  gather(key = "key", value = "value", -songid) %>% 
  mutate(key = tools::toTitleCase(key))
```


```{r}
raw %>% 
  select(danceability:tempo, duration_ms) %>% 
  gather() %>% 
  mutate(key = tools::toTitleCase(key)) %>% 
  ggplot() +
  geom_histogram(aes(x = value), fill = "blue") +
  geom_vline(data = songs, aes(xintercept = value, colour = songid)) +
  facet_wrap(~key, scales = "free")
```

## Audio Analysis
```{r}
get_sections <- function(x) {
  s <- get_track_audio_analysis(x)
  sections <- s$sections
  
  sections <- select(sections, start, loudness, tempo)
}

audio_song <- map_dfr(c(params$song1id, params$song2id), get_sections, .id = "songid") %>% 
  gather(key = "analysis", value = "value", -songid, -start)

ggplot(audio_song, aes(x = start, y = value, colour = songid)) +
  geom_line() +
  facet_wrap(~analysis, ncol = 1, scales = "free_y")
```

